//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GABES.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_BEM3DTYPE                   130
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDB_BITMAP1                     312
#define IDB_FILE_LARGE                  312
#define IDB_BITMAP2                     313
#define IDR_TOOLBAR1                    314
#define IDB_BITMAP3                     317
#define IDR_VIEWOPTIONS_TOOLBAR         318
#define IDB_BCS_LARGE                   321
#define IDI_ICON_MODEL                  323
#define IDI_ICON_SUBSET                 324
#define IDR_SUBSETS_MENU                325
#define IDD_DLG_RANGE_SUBSET            326
#define IDD_DLG_PARTIAL_ENCASTER        330
#define IDD_DLG_DISPLACEMENT_VECTOR     332
#define IDD_DLG_NORMAL_DISPLACEMENT     334
#define IDD_DLG_TRACTION_VECTOR         335
#define IDD_DLG_NORMAL_TRACTION         336
#define IDB_BEM_LARGE                   336
#define IDD_DLG_PRESSURE                337
#define IDD_DLG_SET_MATERIAL_PROPERTIES 338
#define IDD_DLG_SET_INTEGRATION_PARAMETERS 341
#define IDB_RULE_003_PTS                347
#define IDB_RULE_004_PTS                348
#define IDB_RULE_007_PTS                349
#define IDB_RULE_013_PTS                350
#define IDB_RULE_028_PTS                351
#define IDB_RULE_052_PTS                352
#define IDB_RULE_056_PTS                353
#define IDB_RULE_104_PTS                354
#define IDB_RULE_112_PTS                355
#define IDB_RULE_208_PTS                356
#define IDB_RULE_001_PTS                357
#define IDD_DLG_SET_DEFORMATION_SCALE   360
#define IDD_DLG_WAIT_LENGTHY_OPERATION  362
#define IDD_DLG_UNITS_SYSTEM            364
#define IDD_DLG_MESH_TYPE               364
#define IDD_DLG_PALETTE_SETTINGS        367
#define IDR_MESH_Z_AXIS                 380
#define IDR_MESH_Y_AXIS                 382
#define IDR_MESH_X_AXIS                 383
#define IDD_DLG_SET_RAM_BAIL            384
#define IDD_DLG_SOLVER_PARAMETERS       386
#define IDD_DLG_DOMAIN_NODE_RESPONSE    389
#define IDD_DLG_GENERATE_DOMAIN_RESPONSE_REPORT 391
#define IDB_MODELING_LARGE              393
#define IDI_ICON_REFFRAME               394
#define IDI_ICON_REFFRAMES              395
#define IDD_DLG_REFFRAME                396
#define IDB_ADAPTIVE_CRITERION          400
#define IDB_BITMAP4                     400
#define IDC_CMB_COOR_SYS_RANGE_SUBSET   1000
#define IDC_CMB_COORD_SYSTEM            1000
#define IDC_STATIC_DIM1                 1001
#define IDC_STATIC_DIM2                 1002
#define IDC_STATIC_DIM3                 1003
#define IDC_EDIT_MIN_DIM1               1004
#define IDC_EDIT_MIN_DIM2               1005
#define IDC_CHECK_INCLUDE_MIN1          1006
#define IDC_EDIT_MIN_DIM3               1007
#define IDC_CHECK_ENCASTER_UX           1007
#define IDC_EDIT_MAX_DIM1               1008
#define IDC_CHECK_ENCASTER_UY           1008
#define IDC_EDIT_MAX_DIM2               1009
#define IDC_CHECK_ENCASTER_UZ           1009
#define IDC_CHECK_UX                    1009
#define IDC_EDIT_MAX_DIM3               1010
#define IDC_CHECK_UY                    1010
#define IDC_CHECK_INCLUDE_MIN2          1011
#define IDC_CHECK_UZ                    1011
#define IDC_CHECK_INCLUDE_MIN3          1012
#define IDC_EDIT_UX                     1012
#define IDC_EDIT_UY                     1013
#define IDC_EDIT_UN                     1013
#define IDC_EDIT_CENTER_X               1013
#define IDC_EDIT_UZ                     1014
#define IDC_EDIT_CENTER_Y               1014
#define IDC_EDIT_TX                     1015
#define IDC_EDIT_CENTER_Z               1015
#define IDC_CHECK_INCLUDE_MAX1          1016
#define IDC_EDIT_TY                     1016
#define IDC_CHECK_INCLUDE_MAX2          1017
#define IDC_EDIT_TZ                     1017
#define IDC_CHECK6                      1018
#define IDC_CHECK_INCLUDE_MAX3          1018
#define IDC_EDIT_TN                     1018
#define IDC_RADIO_E                     1019
#define IDC_EDIT_VK_PHI                 1019
#define IDC_EDIT_VECTOR_X               1019
#define IDC_RADIO_G                     1020
#define IDC_EDIT_VECTOR_Y               1020
#define IDC_EDIT_E                      1021
#define IDC_EDIT_VK_THETA               1021
#define IDC_EDIT_VECTOR_Z               1021
#define IDC_EDIT_G                      1022
#define IDC_COMBO_INTEGRATION_RULE      1022
#define IDC_EDIT_V                      1023
#define IDC_STATIC_IMAGES               1023
#define IDC_CHECK_AUTO_COMPUTE          1024
#define IDC_EDIT_SCALE                  1025
#define IDC_PROGRESS_ADVANCE            1026
#define IDC_STATIC_ADVANCE              1028
#define IDC_COMBO_UNIT_SYSTEM           1029
#define IDC_COMBO_MESH_TYPE             1029
#define IDC_COMBO_NUMBER_FORMAT         1030
#define IDC_EDIT_NUM_DECIMALS           1031
#define IDC_SPIN1                       1032
#define IDC_STATIC_TIME                 1034
#define IDC_STATIC_CURRENT_JOB          1035
#define IDC_EDIT_RAM_BAIL               1036
#define IDC_RADIO_DIRECT_EVALUATION     1037
#define IDC_EDIT_TOTAL_RAM              1037
#define IDC_RADIO_RIGID_BODY_TRANSLATION 1038
#define IDC_SLIDER_RAM_BAIL             1038
#define IDC_CHECK_AUTO_MATRIX_BAILS     1039
#define IDC_SLIDER_Q_MATRIX_BAIL        1040
#define IDC_EDIT_Q_MATRIX_BAIL          1041
#define IDC_SLIDER_R_MATRIX_BAIL        1042
#define IDC_EDIT_R_MATRIX_BAIL          1043
#define IDC_SLIDER_A_MATRIX_BAIL        1044
#define IDC_EDIT_A_MATRIX_BAIL          1045
#define IDC_STATIC_Q_BAIL               1046
#define IDC_STATIC_R_BAIL               1047
#define IDC_STATIC_A_BAIL               1048
#define IDC_STATIC_Q_GB                 1049
#define IDC_STATIC_R_GB                 1050
#define IDC_STATIC_A_GB                 1051
#define IDC_COMBO_SOLVER                1052
#define IDC_EDIT_EPS                    1053
#define IDC_EDIT_STEPS                  1054
#define IDC_SPIN_STEPS                  1055
#define IDC_EDIT_X                      1056
#define IDC_EDIT_Y                      1057
#define IDC_EDIT_Z                      1058
#define IDC_CHECK_U1                    1059
#define IDC_EDIT_U2                     1061
#define IDC_CHECK_U2                    1062
#define IDC_CHECK_U3                    1063
#define IDC_CHECK_U                     1064
#define IDC_EDIT_U3                     1065
#define IDC_EDIT_U                      1066
#define IDC_CHECK_SIG11                 1067
#define IDC_CHECK_SIG22                 1068
#define IDC_CHECK_SIG33                 1069
#define IDC_CHECK_SIG12                 1070
#define IDC_EDIT_SIG11                  1071
#define IDC_EDIT_SIG22                  1072
#define IDC_EDIT_SIG33                  1073
#define IDC_EDIT_SIG12                  1074
#define IDC_CHECK_SIG23                 1075
#define IDC_EDIT_SIG23                  1076
#define IDC_CHECK_SIG31                 1077
#define IDC_EDIT_SIG31                  1078
#define IDC_CHECK_EPS11                 1079
#define IDC_CHECK_EPS22                 1080
#define IDC_CHECK_EPS33                 1081
#define IDC_CHECK_EPS12                 1082
#define IDC_EDIT_EPS11                  1083
#define IDC_EDIT_EPS22                  1084
#define IDC_EDIT_EPS33                  1085
#define IDC_EDIT_EPS12                  1086
#define IDC_CHECK_EPS23                 1087
#define IDC_EDIT_EPS23                  1088
#define IDC_CHECK_EPS31                 1089
#define IDC_EDIT_EPS31                  1090
#define ID_CALCULATE                    1091
#define IDC_EDIT_U1                     1092
#define IDC_CHECK_SIG_VON_MISES         1093
#define IDC_RADIO_INPUT_FILE            1093
#define IDC_EDIT_SIG_VON_MISES          1094
#define IDC_RADIO_GENERATE_GRID         1094
#define IDC_EDIT_INPUT_FILE             1095
#define IDC_BUTTON_INPUT_FILE           1096
#define IDC_CHECK_SIG_VON_MISES2        1099
#define IDC_BUTTON_OPEN_GRID_GENERATION_DIALOG 1101
#define IDC_CHECK_GRID_GENERATED        1102
#define IDC_EDIT_OUTPUT_FILE            1103
#define IDC_EDIT_OX                     1103
#define IDC_BUTTON_OUTPUT_FILE          1104
#define IDC_EDIT_OY                     1104
#define IDC_EDIT_OZ                     1105
#define IDC_EDIT_V1X                    1106
#define IDC_COMBO_PLANE                 1107
#define IDC_EDIT_V1Y                    1108
#define IDC_EDIT_V1Z                    1109
#define IDC_BUTTON_SET_ORIGIN           1113
#define IDC_EDIT_FRAME_NAME             1114
#define IDC_BUTTON_APPLY                1115
#define IDC_EDIT_INPUT_X                1116
#define IDC_EDIT_INPUT_Y                1117
#define IDC_EDIT_INPUT_Z                1118
#define IDC_BUTTON_SET_VECTOR1          1119
#define ID_BUTTON_ADD                   1120
#define ID_VIEW_MOUSEACTION_VERTEX_SELECTION 1120
#define ID_VIEW_MOUSEACTION_POINT_SELECTION 1120
#define IDC_EDIT_V2X                    1121
#define IDC_EDIT_V2Y                    1122
#define IDC_EDIT_V2Z                    1123
#define IDC_BUTTON_SET_VECTOR2          1124
#define IDC_RADIO_SET_ORIGIN_GRAPHICALLY 1124
#define IDC_RADIO_SET_VECTOR1_GRAPHICALLY 1125
#define IDC_BTN_ORIGIN_PICK_SEL_POINT   1125
#define IDC_RADIO_SET_VECTOR2_GRAPHICALLY 1126
#define IDC_BTN_ORIGIN_PICK_CENTER_3PTS 1126
#define IDC_STATIC_VEC1                 1127
#define IDC_STATIC_VEC2                 1128
#define IDC_COMBO_REF_FRAMES            1129
#define IDC_BTN_VECTOR1_PICK_SEL_POINT  1130
#define IDC_SLIDER_MIN_DIM1             1130
#define IDC_BTN_VECTOR1_PICK_SELECTED_ELEMENT_NORMAL 1131
#define IDC_SLIDER_MAX_DIM1             1131
#define IDC_SLIDER_MIN_DIM2             1132
#define IDC_SLIDER_MAX_DIM2             1133
#define IDC_BTN_VECTOR2_PICK_SEL_POINT  1134
#define IDC_SLIDER_MIN_DIM3             1134
#define IDC_BTN_VECTOR2_PICK_SELECTED_ELEMENT_NORMAL 1135
#define IDC_SLIDER_MAX_DIM3             1135
#define IDC_BTN_APPLY                   1136
#define IDC_EDIT_SUBSET_NAME            1138
#define IDC_RADIO_ADAPTIVE_CRITERION    1140
#define IDC_RADIO_FIXED_CUBATURE_RULE   1141
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_FILE_LOAD_OBJECT_FILE        32771
#define ID_VIEW_DUMMY                   32777
#define ID_VIEW_ORIENTATION_STAT        32778
#define ID_VIEW_FRONT                   32779
#define ID_VIEW_RIGHT                   32780
#define ID_VIEW_TOP                     32781
#define ID_VIEW_BACK                    32782
#define ID_VIEW_LEFT                    32783
#define ID_VIEW_BOTTOM                  32784
#define ID_VIEW_FILLMODE                32785
#define ID_VIEW_VIEW_MODE_STAT          32786
#define ID_BCS_FULLY_ENCASTER           32788
#define ID_VIEW_DUMMY2                  32789
#define ID_VIEW_DUMMY3                  32790
#define ID_VIEW_MOUSEACTION_STAT        32791
#define ID_VIEW_MOUSEACTION_ROTATE      32792
#define ID_VIEW_MOUSEACTION_SELECT      32793
#define ID_VIEW_MOUSEACTION_ELEMENT_SELECTION 32793
#define ID_MODELING_CREATE_ELEMENT_SET_FROM_SELECTION 32794
#define ID_MODELING_IMPORT_ELEMENT_SET_FROM_OBJ_FILE 32795
#define ID_MODELING_CREATE_RANGE_ELEMENT_SET 32797
#define ID_RENAME                       32798
#define ID_SUBSET_RENAME                32799
#define ID_DUMMY_RENAME                 32800
#define ID_DUMMY_DELETE                 32801
#define ID_SUBSETS_DELETE               32802
#define ID_SUBSET_DELETE                32803
#define ID_FILE_DELETE_MODEL            32804
#define ID_BCS_PARTIAL_ENCASTREMENT     32805
#define ID_BCS_DISPLACEMENT_VECTOR      32806
#define ID_BCS_NORMAL_DISPLACEMENT      32807
#define ID_BCS_TRACTION_VECTOR          32808
#define ID_BCS_NORMAL_TRACTION          32810
#define ID_BCS_PRESSURE                 32811
#define ID_BEM_COEFFICIENT_MATRICES     32812
#define ID_BEM_SOLVE_BOUNDARY_VALUE_PROBLEM 32813
#define ID_BEM_SHOW_DEFORMATION         32814
#define ID_BEM_SET_MATERIAL_PROPERTIES  32815
#define ID_BEM_POSTTREATMENT_MODE       32817
#define ID_BEM_SET_INTEGRATION_PARAMETERS 32818
#define ID_BEM_SET_DEFORMATION_SCALE    32819
#define ID_BCS_CHECK_SHOW_FIXATIONS     32821
#define ID_BCS_CHECK_SHOW_DISPLACEMENT_VECTORS 32822
#define ID_BCS_CHECK_SHOW_TRACTION_VECTORS 32823
#define ID_VIEW_DUMMY4                  32824
#define ID_VIEW_OUTPUTMODE_STAT         32825
#define ID_VIEW_OUTPUTMODE              32826
#define ID_VIEW_VARIABLE_STAT           32827
#define ID_VIEW_VARIABLE                32828
#define ID_VIEW_DUMMY5                  32829
#define ID_BEM_SET_UNITSYSTEM           32830
#define ID_BEM_PALETTE_SETTINGS         32831
#define ID_FILE_LOAD_MESH_FILE          32832
#define ID_BEM_SET_MESHTYPE             32833
#define ID_BEM_SET_MEMORY_BAIL          32834
#define ID_BEM_GET_DOMAIN_NODE_RESPONSE 32835
#define ID_BEM_GENERATE_REPORT          32836
#define ID_VIEW_SHOWNODES               32837
#define ID_VIEW_SHOWPOINTS_MODE         32837
#define ID_MODELING_ADD_FRAME           32838
#define ID_VIEW_MOUSEACTION_NODE_SELECTION 32842
#define ID_VIEW_ISOMETRIC               32846
#define ID_BCS_TRACTION_FREE            32847

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        401
#define _APS_NEXT_COMMAND_VALUE         32848
#define _APS_NEXT_CONTROL_VALUE         1142
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
